Используя метод вращений найти собственные значения и собственные векторы сиvvетрических матриц с погрешностью 0.01.

In [15]:
import numpy as np
import math


def Jakobi_rotation_method(A, eps):
    
    def find_max_el(A):
        max_el = A[0][1]
        ind = (0, 1)
        for i in range(len(A)):
            for j in range(len(A[0])):
                if i != j and abs(A[i][j]) > abs(max_el):
                    max_el = A[i][j]
                    ind = (i, j)
        return (max_el, ind)
     
        
    def make_U(A, max_el_with_ind):
        max_el = max_el_with_ind[0]
        i, j = max_el_with_ind[1][0], max_el_with_ind[1][1]
        U = np.zeros(A.shape)
        phi = 0.5 * math.atan(2*max_el/(A[i][i] - A[j][j]))
        for ind1 in range(len(U)):
            for ind2 in range(len(U[0])):
                if (ind1, ind2) == (i, j):
                    U[ind1][ind2] = -math.sin(phi)
                elif (ind1, ind2) == (j, i):
                    U[ind1][ind2] = math.sin(phi)
                elif (ind1, ind2) == (i, i) or (ind1, ind2) == (j, j):
                    U[ind1][ind2] = math.cos(phi)
                elif ind1 == ind2:
                    U[ind1][ind2] = 1
        return U
    
    def t(A):
        tmp = []
        for l in range(len(A)):
            for m in range(l+1, (len(A))):
                tmp.append(A[l][m])
        return sum([el ** 2 for el in tmp]) ** 0.5
        
        
    max_el_with_ind = find_max_el(A)
    U = make_U(A, max_el_with_ind)
    A_new = U.transpose() @ A @ U
    num_of_iter = 1
    
    eigenvector = U
    while t(A_new) > eps:
        num_of_iter += 1
        A = A_new
        max_el_with_ind = find_max_el(A)
        U = make_U(A, max_el_with_ind)
        eigenvector = eigenvector @ U
        A_new = U.transpose() @ A @ U
        
    print("A =", np.around(A_new, decimals=7),"number of iterations = {}".format(num_of_iter), 
          "Собственные векторы:", eigenvector, sep = '\n')
    
    def find_angle(a, b):
        return math.acos(np.dot(a, b)/np.dot(a, a) ** 0.5 * np.dot(b, b) ** 0.5)
    
    eigenvector1 = np.transpose(eigenvector)[0]
    eigenvector2 = np.transpose(eigenvector)[1]
    eigenvector3 = np.transpose(eigenvector)[2]
    print("angle between eigenvector 1 and eigenvector 2:", find_angle(eigenvector1, eigenvector2))
    print("angle between eigenvector 1 and eigenvector 3:", find_angle(eigenvector1, eigenvector3))
    print("angle between eigenvector 2 and eigenvector 3:", find_angle(eigenvector2, eigenvector3))

In [16]:
A = np.array([[-4, 1, -7],
             [1, 9, 1], 
             [-7, 1, 7]])

Jakobi_rotation_method(A, 1e-6)


A =
[[-7.5105179  0.         0.       ]
 [ 0.         8.9609142  0.       ]
 [ 0.         0.        10.5496037]]
number of iterations = 6
Собственные векторы:
[[ 0.8955452   0.20283871 -0.39604955]
 [-0.0807442   0.94935914  0.30364056]
 [ 0.43758332 -0.23994515  0.86657208]]
angle between eigenvector 1 and eigenvector 2: 1.5707963267948966
angle between eigenvector 1 and eigenvector 3: 1.5707963267948968
angle between eigenvector 2 and eigenvector 3: 1.5707963267948966
