Решить СЛАУ методом простой итерации и методом Зейделя с погрешностью 0.01.

In [5]:
import numpy as np


def norma_matr(arr):
    sums = [sum(abs(arr[i])) for i in range(len(arr))]
    return max(sums)
    
def norma_vect(v):
    return sum([abs(el) for el in v])

def MPI(A, b, eps=0.01):
    n = len(A)
    B = np.zeros((n, n))
    d = np.zeros(n)
    for i in range(n):
        for j in range(n):
            if i == j:
                B[i][i] = 0
            else:    
                 B[i][j] = -A[i][j] / A[i][i]
        d[i] = b[i]/A[i][i]
                         
    x = d
    x_new = np.dot(B, x) + d
    while norma_vect(x_new - x) > (1-norma_matr(B))/norma_matr(B)*eps:
        x = x_new
        x_new = np.dot(B, x) + d
    return x_new


In [6]:
A = np.array([[16, -2, 0, 7], [-1, 14, -3, 2], [5, 5, 26, 7], [-2, -6, 9, 24]])
b = np.array([50, 2, 273, 11])
x = MPI(A, b)
print(x)

[ 4.39625098  2.82964093  9.67479368 -2.09574867]


In [7]:
def Seidel(A, b, eps=0.01):
    n = len(A)
    B = np.zeros((n, n))
    d = np.zeros(n)
    for i in range(n):
        for j in range(n):
            if i == j:
                B[i][i] = 0
            else:    
                 B[i][j] = -A[i][j] / A[i][i]
        d[i] = b[i]/A[i][i]

    x_new = np.copy(d)
    for i in range(len(x_new)):
        x_new[i] = np.dot(B[i], x_new) + d[i]
    x = np.copy(d)
    while norma_vect(np.dot(A, x_new) - b) > eps:
        x = np.copy(x_new)
        for i in range(len(x_new)):
            x_new[i] = np.dot(B[i], x_new) + d[i]
    return x_new
      

In [8]:
A = np.array([[16, -2, 0, 7], [-1, 14, -3, 2], [5, 5, 26, 7], [-2, -6, 9, 24]])
b = np.array([50, 2, 273, 11])
x = Seidel(A, b)
print(x)

[ 4.39558279  2.82922322  9.67479019 -2.09610862]


In [9]:
np.linalg.solve(A, b)

array([ 4.39571243,  2.82946123,  9.67486954, -2.09606807])